<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Siyu Xie (PID:A16438448)">

<title>class09</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="class09_files/libs/clipboard/clipboard.min.js"></script>
<script src="class09_files/libs/quarto-html/quarto.js"></script>
<script src="class09_files/libs/quarto-html/popper.min.js"></script>
<script src="class09_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="class09_files/libs/quarto-html/anchor.min.js"></script>
<link href="class09_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="class09_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="class09_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="class09_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="class09_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#import-data" id="toc-import-data" class="nav-link active" data-scroll-target="#import-data">1. Import Data</a></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration">1.1 Data exploration</a></li>
  <li><a href="#my-favorate-candy-vs-yours" id="toc-my-favorate-candy-vs-yours" class="nav-link" data-scroll-target="#my-favorate-candy-vs-yours">2. My favorate candy vs yours</a></li>
  <li><a href="#overall-candy-ranking" id="toc-overall-candy-ranking" class="nav-link" data-scroll-target="#overall-candy-ranking">Overall Candy Ranking</a></li>
  <li><a href="#taking-a-look-at-pricepercent" id="toc-taking-a-look-at-pricepercent" class="nav-link" data-scroll-target="#taking-a-look-at-pricepercent">4. Taking a look at pricepercent</a></li>
  <li><a href="#exploring-the-correlation-structure" id="toc-exploring-the-correlation-structure" class="nav-link" data-scroll-target="#exploring-the-correlation-structure">5. Exploring the correlation structure</a></li>
  <li><a href="#principal-component-analysis" id="toc-principal-component-analysis" class="nav-link" data-scroll-target="#principal-component-analysis">6. Principal Component Analysis</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">class09</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Siyu Xie (PID:A16438448) </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>In today’s class we will examine some data about candy from the 538 website.</p>
<section id="import-data" class="level2">
<h2 class="anchored" data-anchor-id="import-data">1. Import Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>candy_file <span class="ot">&lt;-</span> <span class="st">"candy-data.txt"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">=</span> <span class="fu">read.csv</span>(candy_file,<span class="at">row.names=</span><span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             chocolate fruity caramel peanutyalmondy nougat crispedricewafer
100 Grand            1      0       1              0      0                1
3 Musketeers         1      0       0              0      1                0
One dime             0      0       0              0      0                0
One quarter          0      0       0              0      0                0
Air Heads            0      1       0              0      0                0
Almond Joy           1      0       0              1      0                0
             hard bar pluribus sugarpercent pricepercent winpercent
100 Grand       0   1        0        0.732        0.860   66.97173
3 Musketeers    0   1        0        0.604        0.511   67.60294
One dime        0   0        0        0.011        0.116   32.26109
One quarter     0   0        0        0.011        0.511   46.11650
Air Heads       0   0        0        0.906        0.511   52.34146
Almond Joy      0   1        0        0.465        0.767   50.34755</code></pre>
</div>
</div>
</section>
<section id="data-exploration" class="level2">
<h2 class="anchored" data-anchor-id="data-exploration">1.1 Data exploration</h2>
<blockquote class="blockquote">
<p>Q1. How many different candy types in this dataset?</p>
</blockquote>
<p>There are 85 in this dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 85</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q2. How many fruity candy types are in the dataset?</p>
</blockquote>
<p>There are 38 in this dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(candy<span class="sc">$</span>fruity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38</code></pre>
</div>
</div>
</section>
<section id="my-favorate-candy-vs-yours" class="level2">
<h2 class="anchored" data-anchor-id="my-favorate-candy-vs-yours">2. My favorate candy vs yours</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Snickers"</span>,]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 76.67378</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Welch's Fruit Snacks"</span>,]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44.37552</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Warheads"</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         chocolate fruity caramel peanutyalmondy nougat crispedricewafer hard
Warheads         0      1       0              0      0                0    1
         bar pluribus sugarpercent pricepercent winpercent
Warheads   0        0        0.093        0.116    39.0119</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q3. What is your favorite candy in the dataset and what is it’s winpercent value?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Hershey's Kisses"</span>,]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55.37545</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q4. What is the winpercent value for “Kit Kat”?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Kit Kat"</span>,]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 76.7686</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q5. What is the winpercent value for “Tootsie Roll Snack Bars”?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Tootsie Roll Snack Bars"</span>,]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49.6535</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>skimr<span class="sc">::</span><span class="fu">skim</span>(candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">candy</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">chocolate</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">fruity</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">caramel</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">peanutyalmondy</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nougat</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">crispedricewafer</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hard</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">bar</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pluribus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">sugarpercent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">▇▇▇▇▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pricepercent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: left;">▇▇▇▇▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">winpercent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">50.32</td>
<td style="text-align: right;">14.71</td>
<td style="text-align: right;">22.45</td>
<td style="text-align: right;">39.14</td>
<td style="text-align: right;">47.83</td>
<td style="text-align: right;">59.86</td>
<td style="text-align: right;">84.18</td>
<td style="text-align: left;">▃▇▆▅▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>Q6. Is there any variable/column that looks to be on a different scale to the majority of the other columns in the dataset?</p>
</blockquote>
<p>Sugarpercent, pricepercent, and winpercent look different, because they are continuous variables while others are discrete variables.</p>
<blockquote class="blockquote">
<p>Q7. What do you think a zero and one represent for the candy$chocolate column?</p>
</blockquote>
<p>Logical true or false (discrete variables, 1 for true, 0 for false), i.e.&nbsp;does the candy type have chocolate or not.</p>
<blockquote class="blockquote">
<p>Q8. Plot a histogram of winpercent values</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(candy<span class="sc">$</span>winpercent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q8b. Plot a histogram of winpercent values using ggplot</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy)<span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent)<span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy)<span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent)<span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q9. Is the distribution of winpercent values symmetrical?</p>
</blockquote>
<p>No.&nbsp;It’s skewed to the right.</p>
<blockquote class="blockquote">
<p>Q10. Is the center of the distribution above or below 50%?</p>
</blockquote>
<p>The center of the distribution is below 50%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(candy<span class="sc">$</span>winpercent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50.31676</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(candy<span class="sc">$</span>winpercent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  22.45   39.14   47.83   50.32   59.86   84.18 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q11. On average is chocolate candy higher or lower ranked than fruit candy?</p>
</blockquote>
<ul>
<li>first find all chocolate candy</li>
<li>find their winpercent values</li>
<li>calculate the mean of these values</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>chocolate.inds <span class="ot">&lt;-</span> candy<span class="sc">$</span>chocolate <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>chocolate.inds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE
[25]  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE FALSE  TRUE
[37]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE
[49] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE
[61] FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
[73] FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE
[85]  TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>candy[chocolate.inds,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            chocolate fruity caramel peanutyalmondy nougat
100 Grand                           1      0       1              0      0
3 Musketeers                        1      0       0              0      1
Almond Joy                          1      0       0              1      0
Baby Ruth                           1      0       1              1      1
Charleston Chew                     1      0       0              0      1
Hershey's Kisses                    1      0       0              0      0
Hershey's Krackel                   1      0       0              0      0
Hershey's Milk Chocolate            1      0       0              0      0
Hershey's Special Dark              1      0       0              0      0
Junior Mints                        1      0       0              0      0
Kit Kat                             1      0       0              0      0
Peanut butter M&amp;M's                 1      0       0              1      0
M&amp;M's                               1      0       0              0      0
Milk Duds                           1      0       1              0      0
Milky Way                           1      0       1              0      1
Milky Way Midnight                  1      0       1              0      1
Milky Way Simply Caramel            1      0       1              0      0
Mounds                              1      0       0              0      0
Mr Good Bar                         1      0       0              1      0
Nestle Butterfinger                 1      0       0              1      0
Nestle Crunch                       1      0       0              0      0
Peanut M&amp;Ms                         1      0       0              1      0
Reese's Miniatures                  1      0       0              1      0
Reese's Peanut Butter cup           1      0       0              1      0
Reese's pieces                      1      0       0              1      0
Reese's stuffed with pieces         1      0       0              1      0
Rolo                                1      0       1              0      0
Sixlets                             1      0       0              0      0
Nestle Smarties                     1      0       0              0      0
Snickers                            1      0       1              1      1
Snickers Crisper                    1      0       1              1      0
Tootsie Pop                         1      1       0              0      0
Tootsie Roll Juniors                1      0       0              0      0
Tootsie Roll Midgies                1      0       0              0      0
Tootsie Roll Snack Bars             1      0       0              0      0
Twix                                1      0       1              0      0
Whoppers                            1      0       0              0      0
                            crispedricewafer hard bar pluribus sugarpercent
100 Grand                                  1    0   1        0        0.732
3 Musketeers                               0    0   1        0        0.604
Almond Joy                                 0    0   1        0        0.465
Baby Ruth                                  0    0   1        0        0.604
Charleston Chew                            0    0   1        0        0.604
Hershey's Kisses                           0    0   0        1        0.127
Hershey's Krackel                          1    0   1        0        0.430
Hershey's Milk Chocolate                   0    0   1        0        0.430
Hershey's Special Dark                     0    0   1        0        0.430
Junior Mints                               0    0   0        1        0.197
Kit Kat                                    1    0   1        0        0.313
Peanut butter M&amp;M's                        0    0   0        1        0.825
M&amp;M's                                      0    0   0        1        0.825
Milk Duds                                  0    0   0        1        0.302
Milky Way                                  0    0   1        0        0.604
Milky Way Midnight                         0    0   1        0        0.732
Milky Way Simply Caramel                   0    0   1        0        0.965
Mounds                                     0    0   1        0        0.313
Mr Good Bar                                0    0   1        0        0.313
Nestle Butterfinger                        0    0   1        0        0.604
Nestle Crunch                              1    0   1        0        0.313
Peanut M&amp;Ms                                0    0   0        1        0.593
Reese's Miniatures                         0    0   0        0        0.034
Reese's Peanut Butter cup                  0    0   0        0        0.720
Reese's pieces                             0    0   0        1        0.406
Reese's stuffed with pieces                0    0   0        0        0.988
Rolo                                       0    0   0        1        0.860
Sixlets                                    0    0   0        1        0.220
Nestle Smarties                            0    0   0        1        0.267
Snickers                                   0    0   1        0        0.546
Snickers Crisper                           1    0   1        0        0.604
Tootsie Pop                                0    1   0        0        0.604
Tootsie Roll Juniors                       0    0   0        0        0.313
Tootsie Roll Midgies                       0    0   0        1        0.174
Tootsie Roll Snack Bars                    0    0   1        0        0.465
Twix                                       1    0   1        0        0.546
Whoppers                                   1    0   0        1        0.872
                            pricepercent winpercent
100 Grand                          0.860   66.97173
3 Musketeers                       0.511   67.60294
Almond Joy                         0.767   50.34755
Baby Ruth                          0.767   56.91455
Charleston Chew                    0.511   38.97504
Hershey's Kisses                   0.093   55.37545
Hershey's Krackel                  0.918   62.28448
Hershey's Milk Chocolate           0.918   56.49050
Hershey's Special Dark             0.918   59.23612
Junior Mints                       0.511   57.21925
Kit Kat                            0.511   76.76860
Peanut butter M&amp;M's                0.651   71.46505
M&amp;M's                              0.651   66.57458
Milk Duds                          0.511   55.06407
Milky Way                          0.651   73.09956
Milky Way Midnight                 0.441   60.80070
Milky Way Simply Caramel           0.860   64.35334
Mounds                             0.860   47.82975
Mr Good Bar                        0.918   54.52645
Nestle Butterfinger                0.767   70.73564
Nestle Crunch                      0.767   66.47068
Peanut M&amp;Ms                        0.651   69.48379
Reese's Miniatures                 0.279   81.86626
Reese's Peanut Butter cup          0.651   84.18029
Reese's pieces                     0.651   73.43499
Reese's stuffed with pieces        0.651   72.88790
Rolo                               0.860   65.71629
Sixlets                            0.081   34.72200
Nestle Smarties                    0.976   37.88719
Snickers                           0.651   76.67378
Snickers Crisper                   0.651   59.52925
Tootsie Pop                        0.325   48.98265
Tootsie Roll Juniors               0.511   43.06890
Tootsie Roll Midgies               0.011   45.73675
Tootsie Roll Snack Bars            0.325   49.65350
Twix                               0.906   81.64291
Whoppers                           0.848   49.52411</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>chocolate.win <span class="ot">&lt;-</span> candy[chocolate.inds,]<span class="sc">$</span>winpercent</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>chocolate.win</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 66.97173 67.60294 50.34755 56.91455 38.97504 55.37545 62.28448 56.49050
 [9] 59.23612 57.21925 76.76860 71.46505 66.57458 55.06407 73.09956 60.80070
[17] 64.35334 47.82975 54.52645 70.73564 66.47068 69.48379 81.86626 84.18029
[25] 73.43499 72.88790 65.71629 34.72200 37.88719 76.67378 59.52925 48.98265
[33] 43.06890 45.73675 49.65350 81.64291 49.52411</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(chocolate.win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60.92153</code></pre>
</div>
</div>
<ul>
<li>then do the same for fruity candy and compare</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>fruity.inds <span class="ot">&lt;-</span> <span class="fu">as.logical</span> (candy<span class="sc">$</span>fruity)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>candy[fruity.inds, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            chocolate fruity caramel peanutyalmondy nougat
Air Heads                           0      1       0              0      0
Caramel Apple Pops                  0      1       1              0      0
Chewey Lemonhead Fruit Mix          0      1       0              0      0
Chiclets                            0      1       0              0      0
Dots                                0      1       0              0      0
Dum Dums                            0      1       0              0      0
Fruit Chews                         0      1       0              0      0
Fun Dip                             0      1       0              0      0
Gobstopper                          0      1       0              0      0
Haribo Gold Bears                   0      1       0              0      0
Haribo Sour Bears                   0      1       0              0      0
Haribo Twin Snakes                  0      1       0              0      0
Jawbusters                          0      1       0              0      0
Laffy Taffy                         0      1       0              0      0
Lemonhead                           0      1       0              0      0
Lifesavers big ring gummies         0      1       0              0      0
Mike &amp; Ike                          0      1       0              0      0
Nerds                               0      1       0              0      0
Nik L Nip                           0      1       0              0      0
Now &amp; Later                         0      1       0              0      0
Pop Rocks                           0      1       0              0      0
Red vines                           0      1       0              0      0
Ring pop                            0      1       0              0      0
Runts                               0      1       0              0      0
Skittles original                   0      1       0              0      0
Skittles wildberry                  0      1       0              0      0
Smarties candy                      0      1       0              0      0
Sour Patch Kids                     0      1       0              0      0
Sour Patch Tricksters               0      1       0              0      0
Starburst                           0      1       0              0      0
Strawberry bon bons                 0      1       0              0      0
Super Bubble                        0      1       0              0      0
Swedish Fish                        0      1       0              0      0
Tootsie Pop                         1      1       0              0      0
Trolli Sour Bites                   0      1       0              0      0
Twizzlers                           0      1       0              0      0
Warheads                            0      1       0              0      0
Welch's Fruit Snacks                0      1       0              0      0
                            crispedricewafer hard bar pluribus sugarpercent
Air Heads                                  0    0   0        0        0.906
Caramel Apple Pops                         0    0   0        0        0.604
Chewey Lemonhead Fruit Mix                 0    0   0        1        0.732
Chiclets                                   0    0   0        1        0.046
Dots                                       0    0   0        1        0.732
Dum Dums                                   0    1   0        0        0.732
Fruit Chews                                0    0   0        1        0.127
Fun Dip                                    0    1   0        0        0.732
Gobstopper                                 0    1   0        1        0.906
Haribo Gold Bears                          0    0   0        1        0.465
Haribo Sour Bears                          0    0   0        1        0.465
Haribo Twin Snakes                         0    0   0        1        0.465
Jawbusters                                 0    1   0        1        0.093
Laffy Taffy                                0    0   0        0        0.220
Lemonhead                                  0    1   0        0        0.046
Lifesavers big ring gummies                0    0   0        0        0.267
Mike &amp; Ike                                 0    0   0        1        0.872
Nerds                                      0    1   0        1        0.848
Nik L Nip                                  0    0   0        1        0.197
Now &amp; Later                                0    0   0        1        0.220
Pop Rocks                                  0    1   0        1        0.604
Red vines                                  0    0   0        1        0.581
Ring pop                                   0    1   0        0        0.732
Runts                                      0    1   0        1        0.872
Skittles original                          0    0   0        1        0.941
Skittles wildberry                         0    0   0        1        0.941
Smarties candy                             0    1   0        1        0.267
Sour Patch Kids                            0    0   0        1        0.069
Sour Patch Tricksters                      0    0   0        1        0.069
Starburst                                  0    0   0        1        0.151
Strawberry bon bons                        0    1   0        1        0.569
Super Bubble                               0    0   0        0        0.162
Swedish Fish                               0    0   0        1        0.604
Tootsie Pop                                0    1   0        0        0.604
Trolli Sour Bites                          0    0   0        1        0.313
Twizzlers                                  0    0   0        0        0.220
Warheads                                   0    1   0        0        0.093
Welch's Fruit Snacks                       0    0   0        1        0.313
                            pricepercent winpercent
Air Heads                          0.511   52.34146
Caramel Apple Pops                 0.325   34.51768
Chewey Lemonhead Fruit Mix         0.511   36.01763
Chiclets                           0.325   24.52499
Dots                               0.511   42.27208
Dum Dums                           0.034   39.46056
Fruit Chews                        0.034   43.08892
Fun Dip                            0.325   39.18550
Gobstopper                         0.453   46.78335
Haribo Gold Bears                  0.465   57.11974
Haribo Sour Bears                  0.465   51.41243
Haribo Twin Snakes                 0.465   42.17877
Jawbusters                         0.511   28.12744
Laffy Taffy                        0.116   41.38956
Lemonhead                          0.104   39.14106
Lifesavers big ring gummies        0.279   52.91139
Mike &amp; Ike                         0.325   46.41172
Nerds                              0.325   55.35405
Nik L Nip                          0.976   22.44534
Now &amp; Later                        0.325   39.44680
Pop Rocks                          0.837   41.26551
Red vines                          0.116   37.34852
Ring pop                           0.965   35.29076
Runts                              0.279   42.84914
Skittles original                  0.220   63.08514
Skittles wildberry                 0.220   55.10370
Smarties candy                     0.116   45.99583
Sour Patch Kids                    0.116   59.86400
Sour Patch Tricksters              0.116   52.82595
Starburst                          0.220   67.03763
Strawberry bon bons                0.058   34.57899
Super Bubble                       0.116   27.30386
Swedish Fish                       0.755   54.86111
Tootsie Pop                        0.325   48.98265
Trolli Sour Bites                  0.255   47.17323
Twizzlers                          0.116   45.46628
Warheads                           0.116   39.01190
Welch's Fruit Snacks               0.313   44.37552</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fruity.win <span class="ot">&lt;-</span> candy[fruity.inds, ]<span class="sc">$</span>winpercent</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(fruity.win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44.11974</code></pre>
</div>
</div>
<p>A: on average, chocolate candies are ranked higher(60.92%) than fruity candies (44.12%).</p>
<blockquote class="blockquote">
<p>Q12. Is this difference statistically significant?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chocolate.win,fruity.win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  chocolate.win and fruity.win
t = 6.2582, df = 68.882, p-value = 2.871e-08
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 11.44563 22.15795
sample estimates:
mean of x mean of y 
 60.92153  44.11974 </code></pre>
</div>
</div>
<p>A: Since p-value =2.87e-08 &lt; 0.05, so the difference is statistically significant.</p>
</section>
<section id="overall-candy-ranking" class="level2">
<h2 class="anchored" data-anchor-id="overall-candy-ranking">Overall Candy Ranking</h2>
<blockquote class="blockquote">
<p>Q13. What are the five least liked candy types in this set?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">7</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 3 5 6 7</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">order</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4 3 1 2 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>x[<span class="fu">order</span>(x)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 3 5 6 7</code></pre>
</div>
</div>
<p>The order function returns the indices that make the input sorted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>inds <span class="ot">&lt;-</span> <span class="fu">order</span>(candy<span class="sc">$</span>winpercent)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>candy[inds,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            chocolate fruity caramel peanutyalmondy nougat
Nik L Nip                           0      1       0              0      0
Boston Baked Beans                  0      0       0              1      0
Chiclets                            0      1       0              0      0
Super Bubble                        0      1       0              0      0
Jawbusters                          0      1       0              0      0
Root Beer Barrels                   0      0       0              0      0
Sugar Daddy                         0      0       1              0      0
One dime                            0      0       0              0      0
Sugar Babies                        0      0       1              0      0
Haribo Happy Cola                   0      0       0              0      0
Caramel Apple Pops                  0      1       1              0      0
Strawberry bon bons                 0      1       0              0      0
Sixlets                             1      0       0              0      0
Ring pop                            0      1       0              0      0
Chewey Lemonhead Fruit Mix          0      1       0              0      0
Red vines                           0      1       0              0      0
Pixie Sticks                        0      0       0              0      0
Nestle Smarties                     1      0       0              0      0
Candy Corn                          0      0       0              0      0
Charleston Chew                     1      0       0              0      1
Warheads                            0      1       0              0      0
Lemonhead                           0      1       0              0      0
Fun Dip                             0      1       0              0      0
Now &amp; Later                         0      1       0              0      0
Dum Dums                            0      1       0              0      0
Pop Rocks                           0      1       0              0      0
Laffy Taffy                         0      1       0              0      0
Werther's Original Caramel          0      0       1              0      0
Haribo Twin Snakes                  0      1       0              0      0
Dots                                0      1       0              0      0
Runts                               0      1       0              0      0
Tootsie Roll Juniors                1      0       0              0      0
Fruit Chews                         0      1       0              0      0
Welch's Fruit Snacks                0      1       0              0      0
Twizzlers                           0      1       0              0      0
Tootsie Roll Midgies                1      0       0              0      0
Smarties candy                      0      1       0              0      0
One quarter                         0      0       0              0      0
Payday                              0      0       0              1      1
Mike &amp; Ike                          0      1       0              0      0
Gobstopper                          0      1       0              0      0
Trolli Sour Bites                   0      1       0              0      0
Mounds                              1      0       0              0      0
Tootsie Pop                         1      1       0              0      0
Whoppers                            1      0       0              0      0
Tootsie Roll Snack Bars             1      0       0              0      0
Almond Joy                          1      0       0              1      0
Haribo Sour Bears                   0      1       0              0      0
Air Heads                           0      1       0              0      0
Sour Patch Tricksters               0      1       0              0      0
Lifesavers big ring gummies         0      1       0              0      0
Mr Good Bar                         1      0       0              1      0
Swedish Fish                        0      1       0              0      0
Milk Duds                           1      0       1              0      0
Skittles wildberry                  0      1       0              0      0
Nerds                               0      1       0              0      0
Hershey's Kisses                    1      0       0              0      0
Hershey's Milk Chocolate            1      0       0              0      0
Baby Ruth                           1      0       1              1      1
Haribo Gold Bears                   0      1       0              0      0
Junior Mints                        1      0       0              0      0
Hershey's Special Dark              1      0       0              0      0
Snickers Crisper                    1      0       1              1      0
Sour Patch Kids                     0      1       0              0      0
Milky Way Midnight                  1      0       1              0      1
Hershey's Krackel                   1      0       0              0      0
Skittles original                   0      1       0              0      0
Milky Way Simply Caramel            1      0       1              0      0
Rolo                                1      0       1              0      0
Nestle Crunch                       1      0       0              0      0
M&amp;M's                               1      0       0              0      0
100 Grand                           1      0       1              0      0
Starburst                           0      1       0              0      0
3 Musketeers                        1      0       0              0      1
Peanut M&amp;Ms                         1      0       0              1      0
Nestle Butterfinger                 1      0       0              1      0
Peanut butter M&amp;M's                 1      0       0              1      0
Reese's stuffed with pieces         1      0       0              1      0
Milky Way                           1      0       1              0      1
Reese's pieces                      1      0       0              1      0
Snickers                            1      0       1              1      1
Kit Kat                             1      0       0              0      0
Twix                                1      0       1              0      0
Reese's Miniatures                  1      0       0              1      0
Reese's Peanut Butter cup           1      0       0              1      0
                            crispedricewafer hard bar pluribus sugarpercent
Nik L Nip                                  0    0   0        1        0.197
Boston Baked Beans                         0    0   0        1        0.313
Chiclets                                   0    0   0        1        0.046
Super Bubble                               0    0   0        0        0.162
Jawbusters                                 0    1   0        1        0.093
Root Beer Barrels                          0    1   0        1        0.732
Sugar Daddy                                0    0   0        0        0.418
One dime                                   0    0   0        0        0.011
Sugar Babies                               0    0   0        1        0.965
Haribo Happy Cola                          0    0   0        1        0.465
Caramel Apple Pops                         0    0   0        0        0.604
Strawberry bon bons                        0    1   0        1        0.569
Sixlets                                    0    0   0        1        0.220
Ring pop                                   0    1   0        0        0.732
Chewey Lemonhead Fruit Mix                 0    0   0        1        0.732
Red vines                                  0    0   0        1        0.581
Pixie Sticks                               0    0   0        1        0.093
Nestle Smarties                            0    0   0        1        0.267
Candy Corn                                 0    0   0        1        0.906
Charleston Chew                            0    0   1        0        0.604
Warheads                                   0    1   0        0        0.093
Lemonhead                                  0    1   0        0        0.046
Fun Dip                                    0    1   0        0        0.732
Now &amp; Later                                0    0   0        1        0.220
Dum Dums                                   0    1   0        0        0.732
Pop Rocks                                  0    1   0        1        0.604
Laffy Taffy                                0    0   0        0        0.220
Werther's Original Caramel                 0    1   0        0        0.186
Haribo Twin Snakes                         0    0   0        1        0.465
Dots                                       0    0   0        1        0.732
Runts                                      0    1   0        1        0.872
Tootsie Roll Juniors                       0    0   0        0        0.313
Fruit Chews                                0    0   0        1        0.127
Welch's Fruit Snacks                       0    0   0        1        0.313
Twizzlers                                  0    0   0        0        0.220
Tootsie Roll Midgies                       0    0   0        1        0.174
Smarties candy                             0    1   0        1        0.267
One quarter                                0    0   0        0        0.011
Payday                                     0    0   1        0        0.465
Mike &amp; Ike                                 0    0   0        1        0.872
Gobstopper                                 0    1   0        1        0.906
Trolli Sour Bites                          0    0   0        1        0.313
Mounds                                     0    0   1        0        0.313
Tootsie Pop                                0    1   0        0        0.604
Whoppers                                   1    0   0        1        0.872
Tootsie Roll Snack Bars                    0    0   1        0        0.465
Almond Joy                                 0    0   1        0        0.465
Haribo Sour Bears                          0    0   0        1        0.465
Air Heads                                  0    0   0        0        0.906
Sour Patch Tricksters                      0    0   0        1        0.069
Lifesavers big ring gummies                0    0   0        0        0.267
Mr Good Bar                                0    0   1        0        0.313
Swedish Fish                               0    0   0        1        0.604
Milk Duds                                  0    0   0        1        0.302
Skittles wildberry                         0    0   0        1        0.941
Nerds                                      0    1   0        1        0.848
Hershey's Kisses                           0    0   0        1        0.127
Hershey's Milk Chocolate                   0    0   1        0        0.430
Baby Ruth                                  0    0   1        0        0.604
Haribo Gold Bears                          0    0   0        1        0.465
Junior Mints                               0    0   0        1        0.197
Hershey's Special Dark                     0    0   1        0        0.430
Snickers Crisper                           1    0   1        0        0.604
Sour Patch Kids                            0    0   0        1        0.069
Milky Way Midnight                         0    0   1        0        0.732
Hershey's Krackel                          1    0   1        0        0.430
Skittles original                          0    0   0        1        0.941
Milky Way Simply Caramel                   0    0   1        0        0.965
Rolo                                       0    0   0        1        0.860
Nestle Crunch                              1    0   1        0        0.313
M&amp;M's                                      0    0   0        1        0.825
100 Grand                                  1    0   1        0        0.732
Starburst                                  0    0   0        1        0.151
3 Musketeers                               0    0   1        0        0.604
Peanut M&amp;Ms                                0    0   0        1        0.593
Nestle Butterfinger                        0    0   1        0        0.604
Peanut butter M&amp;M's                        0    0   0        1        0.825
Reese's stuffed with pieces                0    0   0        0        0.988
Milky Way                                  0    0   1        0        0.604
Reese's pieces                             0    0   0        1        0.406
Snickers                                   0    0   1        0        0.546
Kit Kat                                    1    0   1        0        0.313
Twix                                       1    0   1        0        0.546
Reese's Miniatures                         0    0   0        0        0.034
Reese's Peanut Butter cup                  0    0   0        0        0.720
                            pricepercent winpercent
Nik L Nip                          0.976   22.44534
Boston Baked Beans                 0.511   23.41782
Chiclets                           0.325   24.52499
Super Bubble                       0.116   27.30386
Jawbusters                         0.511   28.12744
Root Beer Barrels                  0.069   29.70369
Sugar Daddy                        0.325   32.23100
One dime                           0.116   32.26109
Sugar Babies                       0.767   33.43755
Haribo Happy Cola                  0.465   34.15896
Caramel Apple Pops                 0.325   34.51768
Strawberry bon bons                0.058   34.57899
Sixlets                            0.081   34.72200
Ring pop                           0.965   35.29076
Chewey Lemonhead Fruit Mix         0.511   36.01763
Red vines                          0.116   37.34852
Pixie Sticks                       0.023   37.72234
Nestle Smarties                    0.976   37.88719
Candy Corn                         0.325   38.01096
Charleston Chew                    0.511   38.97504
Warheads                           0.116   39.01190
Lemonhead                          0.104   39.14106
Fun Dip                            0.325   39.18550
Now &amp; Later                        0.325   39.44680
Dum Dums                           0.034   39.46056
Pop Rocks                          0.837   41.26551
Laffy Taffy                        0.116   41.38956
Werther's Original Caramel         0.267   41.90431
Haribo Twin Snakes                 0.465   42.17877
Dots                               0.511   42.27208
Runts                              0.279   42.84914
Tootsie Roll Juniors               0.511   43.06890
Fruit Chews                        0.034   43.08892
Welch's Fruit Snacks               0.313   44.37552
Twizzlers                          0.116   45.46628
Tootsie Roll Midgies               0.011   45.73675
Smarties candy                     0.116   45.99583
One quarter                        0.511   46.11650
Payday                             0.767   46.29660
Mike &amp; Ike                         0.325   46.41172
Gobstopper                         0.453   46.78335
Trolli Sour Bites                  0.255   47.17323
Mounds                             0.860   47.82975
Tootsie Pop                        0.325   48.98265
Whoppers                           0.848   49.52411
Tootsie Roll Snack Bars            0.325   49.65350
Almond Joy                         0.767   50.34755
Haribo Sour Bears                  0.465   51.41243
Air Heads                          0.511   52.34146
Sour Patch Tricksters              0.116   52.82595
Lifesavers big ring gummies        0.279   52.91139
Mr Good Bar                        0.918   54.52645
Swedish Fish                       0.755   54.86111
Milk Duds                          0.511   55.06407
Skittles wildberry                 0.220   55.10370
Nerds                              0.325   55.35405
Hershey's Kisses                   0.093   55.37545
Hershey's Milk Chocolate           0.918   56.49050
Baby Ruth                          0.767   56.91455
Haribo Gold Bears                  0.465   57.11974
Junior Mints                       0.511   57.21925
Hershey's Special Dark             0.918   59.23612
Snickers Crisper                   0.651   59.52925
Sour Patch Kids                    0.116   59.86400
Milky Way Midnight                 0.441   60.80070
Hershey's Krackel                  0.918   62.28448
Skittles original                  0.220   63.08514
Milky Way Simply Caramel           0.860   64.35334
Rolo                               0.860   65.71629
Nestle Crunch                      0.767   66.47068
M&amp;M's                              0.651   66.57458
100 Grand                          0.860   66.97173
Starburst                          0.220   67.03763
3 Musketeers                       0.511   67.60294
Peanut M&amp;Ms                        0.651   69.48379
Nestle Butterfinger                0.767   70.73564
Peanut butter M&amp;M's                0.651   71.46505
Reese's stuffed with pieces        0.651   72.88790
Milky Way                          0.651   73.09956
Reese's pieces                     0.651   73.43499
Snickers                           0.651   76.67378
Kit Kat                            0.511   76.76860
Twix                               0.906   81.64291
Reese's Miniatures                 0.279   81.86626
Reese's Peanut Butter cup          0.651   84.18029</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(candy[inds,], <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   chocolate fruity caramel peanutyalmondy nougat
Nik L Nip                  0      1       0              0      0
Boston Baked Beans         0      0       0              1      0
Chiclets                   0      1       0              0      0
Super Bubble               0      1       0              0      0
Jawbusters                 0      1       0              0      0
                   crispedricewafer hard bar pluribus sugarpercent pricepercent
Nik L Nip                         0    0   0        1        0.197        0.976
Boston Baked Beans                0    0   0        1        0.313        0.511
Chiclets                          0    0   0        1        0.046        0.325
Super Bubble                      0    0   0        0        0.162        0.116
Jawbusters                        0    1   0        1        0.093        0.511
                   winpercent
Nik L Nip            22.44534
Boston Baked Beans   23.41782
Chiclets             24.52499
Super Bubble         27.30386
Jawbusters           28.12744</code></pre>
</div>
</div>
<p>A: The five least liked candy types in this set are Nik L Nip, Boston Baked Beans, Chiclets, Super Bubble, Jawbusters.</p>
<blockquote class="blockquote">
<p>Q14. What are the top 5 all time favorite candy types out of this set?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(candy[inds,], <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          chocolate fruity caramel peanutyalmondy nougat
Snickers                          1      0       1              1      1
Kit Kat                           1      0       0              0      0
Twix                              1      0       1              0      0
Reese's Miniatures                1      0       0              1      0
Reese's Peanut Butter cup         1      0       0              1      0
                          crispedricewafer hard bar pluribus sugarpercent
Snickers                                 0    0   1        0        0.546
Kit Kat                                  1    0   1        0        0.313
Twix                                     1    0   1        0        0.546
Reese's Miniatures                       0    0   0        0        0.034
Reese's Peanut Butter cup                0    0   0        0        0.720
                          pricepercent winpercent
Snickers                         0.651   76.67378
Kit Kat                          0.511   76.76860
Twix                             0.906   81.64291
Reese's Miniatures               0.279   81.86626
Reese's Peanut Butter cup        0.651   84.18029</code></pre>
</div>
</div>
<p>A: The top 5 all time favorite candy types out of this set are Snickers, Kit Kat, Twix, Reese’s Miniatures, Reese’s Peanut Butter cup</p>
<blockquote class="blockquote">
<p>Q15. Make a first barplot of candy ranking based on winpercent values.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, <span class="fu">rownames</span>(candy)) <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q16. This is quite ugly, use the reorder() function to get the bars sorted by winpercent?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>my_cols<span class="ot">=</span><span class="fu">rep</span>(<span class="st">"grey"</span>, <span class="fu">nrow</span>(candy))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>my_cols[candy<span class="sc">$</span>fruity <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">=</span> <span class="st">"pink"</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>my_cols[<span class="fu">as.logical</span>(candy<span class="sc">$</span>chocolate)] <span class="ot">=</span> <span class="st">"lightblue"</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>my_cols[<span class="fu">as.logical</span>(candy<span class="sc">$</span>bar)] <span class="ot">=</span> <span class="st">"orange"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>add my custom colors to my barplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, <span class="fu">reorder</span>(<span class="fu">rownames</span>(candy), winpercent))<span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill=</span> my_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"mybarplot.png"</span>, <span class="at">height=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 10 in image</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="mybarplot.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Exported image that is a bit bigger so I can read it</figcaption>
</figure>
</div>
<blockquote class="blockquote">
<p>Q17. What is the worst ranked chocolate candy?</p>
</blockquote>
<p>A: Sixlets is the worst ranked chocolate candy.</p>
<blockquote class="blockquote">
<p>Q18. What is the best ranked fruity candy?</p>
</blockquote>
<p>A: Starburst is the best ranked fruity candy.</p>
</section>
<section id="taking-a-look-at-pricepercent" class="level2">
<h2 class="anchored" data-anchor-id="taking-a-look-at-pricepercent">4. Taking a look at pricepercent</h2>
<p>plot of winpercent vs pricepercent</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, pricepercent)<span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col=</span>my_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, pricepercent, <span class="at">label=</span><span class="fu">rownames</span>(candy)) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col=</span>my_cols) <span class="sc">+</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_label</span>(<span class="at">col=</span>my_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are just too many labels in this above plot to be readable. We can use the <code>ggrepel</code> package to do a better job of placing labels so they minimize text overlap.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, pricepercent, <span class="at">label=</span><span class="fu">rownames</span>(candy)) <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col=</span>my_cols) <span class="sc">+</span> </span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">col=</span>my_cols, <span class="at">size=</span><span class="fl">3.3</span>, <span class="at">max.overlaps =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: ggrepel: 10 unlabeled data points (too many overlaps). Consider
increasing max.overlaps</code></pre>
</div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q19. Which candy type is the highest ranked in terms of winpercent for the least money - i.e.&nbsp;offers the most bang for your buck?</p>
</blockquote>
<p>A: Reese’s Miniature is the highest ranked in terms of winpercent for the least money (relative lowest pricepercent).</p>
<blockquote class="blockquote">
<p>Q20. What are the top 5 most expensive candy types in the dataset and of these which is the least popular?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>ord <span class="ot">&lt;-</span> <span class="fu">order</span>(candy<span class="sc">$</span>pricepercent, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(candy[ord,<span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">12</span>)],<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         pricepercent winpercent
Nik L Nip                       0.976   22.44534
Nestle Smarties                 0.976   37.88719
Ring pop                        0.965   35.29076
Hershey's Krackel               0.918   62.28448
Hershey's Milk Chocolate        0.918   56.49050</code></pre>
</div>
</div>
<p>A: The top 5 most expensive candy types are Nik L Nip, Nestle Smarties, Ring Pop, Mr.&nbsp;Good Bar, Hershey’s Special Dark. Of these, the least popular is Nik L Nip.</p>
<blockquote class="blockquote">
<p>Optional Q21.Make a barplot again with geom_col() this time using pricepercent and then improve this step by step, first ordering the x-axis by value and finally making a so called “dot chat” or “lollipop” chart by swapping geom_col() for geom_point() + geom_segment().</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(pricepercent, <span class="fu">reorder</span>(<span class="fu">rownames</span>(candy), pricepercent)) <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill=</span>my_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(pricepercent, <span class="fu">reorder</span>(<span class="fu">rownames</span>(candy), pricepercent)) <span class="sc">+</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">yend =</span> <span class="fu">reorder</span>(<span class="fu">rownames</span>(candy), pricepercent), </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xend =</span> <span class="dv">0</span>), <span class="at">col=</span> my_cols) <span class="sc">+</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="exploring-the-correlation-structure" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-correlation-structure">5. Exploring the correlation structure</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>cjj <span class="ot">&lt;-</span> <span class="fu">cor</span>(candy)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cjj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q22. Examining this plot what two variables are anti-correlated (i.e.&nbsp;have minus values)?</p>
</blockquote>
<p>A: fruity and chocolate, caramel, peanutyalmondy, nougat, crispedricewafer, bar, pricepercent, winpercent, respectively, are anti-correlated; chocoalte and hard are also anti-correlated.</p>
<blockquote class="blockquote">
<p>Q23. Similarly, what two variables are most positively correlated?</p>
</blockquote>
<p>A: chocolate and bar, chocolate and winpercent are most positively correlated.</p>
</section>
<section id="principal-component-analysis" class="level2">
<h2 class="anchored" data-anchor-id="principal-component-analysis">6. Principal Component Analysis</h2>
<p>We will perform a PCA of the candy. Key-question: do we need to scale the data before PCA? (Yes!)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(candy, <span class="at">scale=</span><span class="cn">TRUE</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2    PC3     PC4    PC5     PC6     PC7
Standard deviation     2.0788 1.1378 1.1092 1.07533 0.9518 0.81923 0.81530
Proportion of Variance 0.3601 0.1079 0.1025 0.09636 0.0755 0.05593 0.05539
Cumulative Proportion  0.3601 0.4680 0.5705 0.66688 0.7424 0.79830 0.85369
                           PC8     PC9    PC10    PC11    PC12
Standard deviation     0.74530 0.67824 0.62349 0.43974 0.39760
Proportion of Variance 0.04629 0.03833 0.03239 0.01611 0.01317
Cumulative Proportion  0.89998 0.93832 0.97071 0.98683 1.00000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pca<span class="sc">$</span>x[,<span class="dv">1</span>], pca<span class="sc">$</span>x[,<span class="dv">2</span>], <span class="at">col=</span>my_cols, <span class="at">pch=</span><span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Make a ggplot version of this figure</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a new data-frame with our PCA results and candy data</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(candy, pca<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>my_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            chocolate fruity caramel peanutyalmondy nougat
100 Grand                           1      0       1              0      0
3 Musketeers                        1      0       0              0      1
One dime                            0      0       0              0      0
One quarter                         0      0       0              0      0
Air Heads                           0      1       0              0      0
Almond Joy                          1      0       0              1      0
Baby Ruth                           1      0       1              1      1
Boston Baked Beans                  0      0       0              1      0
Candy Corn                          0      0       0              0      0
Caramel Apple Pops                  0      1       1              0      0
Charleston Chew                     1      0       0              0      1
Chewey Lemonhead Fruit Mix          0      1       0              0      0
Chiclets                            0      1       0              0      0
Dots                                0      1       0              0      0
Dum Dums                            0      1       0              0      0
Fruit Chews                         0      1       0              0      0
Fun Dip                             0      1       0              0      0
Gobstopper                          0      1       0              0      0
Haribo Gold Bears                   0      1       0              0      0
Haribo Happy Cola                   0      0       0              0      0
Haribo Sour Bears                   0      1       0              0      0
Haribo Twin Snakes                  0      1       0              0      0
Hershey's Kisses                    1      0       0              0      0
Hershey's Krackel                   1      0       0              0      0
Hershey's Milk Chocolate            1      0       0              0      0
Hershey's Special Dark              1      0       0              0      0
Jawbusters                          0      1       0              0      0
Junior Mints                        1      0       0              0      0
Kit Kat                             1      0       0              0      0
Laffy Taffy                         0      1       0              0      0
Lemonhead                           0      1       0              0      0
Lifesavers big ring gummies         0      1       0              0      0
Peanut butter M&amp;M's                 1      0       0              1      0
M&amp;M's                               1      0       0              0      0
Mike &amp; Ike                          0      1       0              0      0
Milk Duds                           1      0       1              0      0
Milky Way                           1      0       1              0      1
Milky Way Midnight                  1      0       1              0      1
Milky Way Simply Caramel            1      0       1              0      0
Mounds                              1      0       0              0      0
Mr Good Bar                         1      0       0              1      0
Nerds                               0      1       0              0      0
Nestle Butterfinger                 1      0       0              1      0
Nestle Crunch                       1      0       0              0      0
Nik L Nip                           0      1       0              0      0
Now &amp; Later                         0      1       0              0      0
Payday                              0      0       0              1      1
Peanut M&amp;Ms                         1      0       0              1      0
Pixie Sticks                        0      0       0              0      0
Pop Rocks                           0      1       0              0      0
Red vines                           0      1       0              0      0
Reese's Miniatures                  1      0       0              1      0
Reese's Peanut Butter cup           1      0       0              1      0
Reese's pieces                      1      0       0              1      0
Reese's stuffed with pieces         1      0       0              1      0
Ring pop                            0      1       0              0      0
Rolo                                1      0       1              0      0
Root Beer Barrels                   0      0       0              0      0
Runts                               0      1       0              0      0
Sixlets                             1      0       0              0      0
Skittles original                   0      1       0              0      0
Skittles wildberry                  0      1       0              0      0
Nestle Smarties                     1      0       0              0      0
Smarties candy                      0      1       0              0      0
Snickers                            1      0       1              1      1
Snickers Crisper                    1      0       1              1      0
Sour Patch Kids                     0      1       0              0      0
Sour Patch Tricksters               0      1       0              0      0
Starburst                           0      1       0              0      0
Strawberry bon bons                 0      1       0              0      0
Sugar Babies                        0      0       1              0      0
Sugar Daddy                         0      0       1              0      0
Super Bubble                        0      1       0              0      0
Swedish Fish                        0      1       0              0      0
Tootsie Pop                         1      1       0              0      0
Tootsie Roll Juniors                1      0       0              0      0
Tootsie Roll Midgies                1      0       0              0      0
Tootsie Roll Snack Bars             1      0       0              0      0
Trolli Sour Bites                   0      1       0              0      0
Twix                                1      0       1              0      0
Twizzlers                           0      1       0              0      0
Warheads                            0      1       0              0      0
Welch's Fruit Snacks                0      1       0              0      0
Werther's Original Caramel          0      0       1              0      0
Whoppers                            1      0       0              0      0
                            crispedricewafer hard bar pluribus sugarpercent
100 Grand                                  1    0   1        0        0.732
3 Musketeers                               0    0   1        0        0.604
One dime                                   0    0   0        0        0.011
One quarter                                0    0   0        0        0.011
Air Heads                                  0    0   0        0        0.906
Almond Joy                                 0    0   1        0        0.465
Baby Ruth                                  0    0   1        0        0.604
Boston Baked Beans                         0    0   0        1        0.313
Candy Corn                                 0    0   0        1        0.906
Caramel Apple Pops                         0    0   0        0        0.604
Charleston Chew                            0    0   1        0        0.604
Chewey Lemonhead Fruit Mix                 0    0   0        1        0.732
Chiclets                                   0    0   0        1        0.046
Dots                                       0    0   0        1        0.732
Dum Dums                                   0    1   0        0        0.732
Fruit Chews                                0    0   0        1        0.127
Fun Dip                                    0    1   0        0        0.732
Gobstopper                                 0    1   0        1        0.906
Haribo Gold Bears                          0    0   0        1        0.465
Haribo Happy Cola                          0    0   0        1        0.465
Haribo Sour Bears                          0    0   0        1        0.465
Haribo Twin Snakes                         0    0   0        1        0.465
Hershey's Kisses                           0    0   0        1        0.127
Hershey's Krackel                          1    0   1        0        0.430
Hershey's Milk Chocolate                   0    0   1        0        0.430
Hershey's Special Dark                     0    0   1        0        0.430
Jawbusters                                 0    1   0        1        0.093
Junior Mints                               0    0   0        1        0.197
Kit Kat                                    1    0   1        0        0.313
Laffy Taffy                                0    0   0        0        0.220
Lemonhead                                  0    1   0        0        0.046
Lifesavers big ring gummies                0    0   0        0        0.267
Peanut butter M&amp;M's                        0    0   0        1        0.825
M&amp;M's                                      0    0   0        1        0.825
Mike &amp; Ike                                 0    0   0        1        0.872
Milk Duds                                  0    0   0        1        0.302
Milky Way                                  0    0   1        0        0.604
Milky Way Midnight                         0    0   1        0        0.732
Milky Way Simply Caramel                   0    0   1        0        0.965
Mounds                                     0    0   1        0        0.313
Mr Good Bar                                0    0   1        0        0.313
Nerds                                      0    1   0        1        0.848
Nestle Butterfinger                        0    0   1        0        0.604
Nestle Crunch                              1    0   1        0        0.313
Nik L Nip                                  0    0   0        1        0.197
Now &amp; Later                                0    0   0        1        0.220
Payday                                     0    0   1        0        0.465
Peanut M&amp;Ms                                0    0   0        1        0.593
Pixie Sticks                               0    0   0        1        0.093
Pop Rocks                                  0    1   0        1        0.604
Red vines                                  0    0   0        1        0.581
Reese's Miniatures                         0    0   0        0        0.034
Reese's Peanut Butter cup                  0    0   0        0        0.720
Reese's pieces                             0    0   0        1        0.406
Reese's stuffed with pieces                0    0   0        0        0.988
Ring pop                                   0    1   0        0        0.732
Rolo                                       0    0   0        1        0.860
Root Beer Barrels                          0    1   0        1        0.732
Runts                                      0    1   0        1        0.872
Sixlets                                    0    0   0        1        0.220
Skittles original                          0    0   0        1        0.941
Skittles wildberry                         0    0   0        1        0.941
Nestle Smarties                            0    0   0        1        0.267
Smarties candy                             0    1   0        1        0.267
Snickers                                   0    0   1        0        0.546
Snickers Crisper                           1    0   1        0        0.604
Sour Patch Kids                            0    0   0        1        0.069
Sour Patch Tricksters                      0    0   0        1        0.069
Starburst                                  0    0   0        1        0.151
Strawberry bon bons                        0    1   0        1        0.569
Sugar Babies                               0    0   0        1        0.965
Sugar Daddy                                0    0   0        0        0.418
Super Bubble                               0    0   0        0        0.162
Swedish Fish                               0    0   0        1        0.604
Tootsie Pop                                0    1   0        0        0.604
Tootsie Roll Juniors                       0    0   0        0        0.313
Tootsie Roll Midgies                       0    0   0        1        0.174
Tootsie Roll Snack Bars                    0    0   1        0        0.465
Trolli Sour Bites                          0    0   0        1        0.313
Twix                                       1    0   1        0        0.546
Twizzlers                                  0    0   0        0        0.220
Warheads                                   0    1   0        0        0.093
Welch's Fruit Snacks                       0    0   0        1        0.313
Werther's Original Caramel                 0    1   0        0        0.186
Whoppers                                   1    0   0        1        0.872
                            pricepercent winpercent         PC1           PC2
100 Grand                          0.860   66.97173 -3.81986175 -0.5935787670
3 Musketeers                       0.511   67.60294 -2.79602364 -1.5196062111
One dime                           0.116   32.26109  1.20258363  0.1718120657
One quarter                        0.511   46.11650  0.44865378  0.4519735621
Air Heads                          0.511   52.34146  0.70289922 -0.5731343263
Almond Joy                         0.767   50.34755 -2.46833834  0.7035501120
Baby Ruth                          0.767   56.91455 -4.10531223 -2.1000967736
Boston Baked Beans                 0.511   23.41782  0.71385813  1.2098216537
Candy Corn                         0.325   38.01096  1.01357204  0.2834319621
Caramel Apple Pops                 0.325   34.51768  0.81049645 -1.6960889498
Charleston Chew                    0.511   38.97504 -2.15436587 -1.9304213037
Chewey Lemonhead Fruit Mix         0.511   36.01763  1.65268482  0.0726434944
Chiclets                           0.325   24.52499  2.38180817  0.4430926071
Dots                               0.511   42.27208  1.51249936  0.1623958592
Dum Dums                           0.034   39.46056  2.14430933 -1.8388386160
Fruit Chews                        0.034   43.08892  2.26133763  0.5818322520
Fun Dip                            0.325   39.18550  1.82383348 -1.7828662094
Gobstopper                         0.453   46.78335  1.96047812 -1.0584680267
Haribo Gold Bears                  0.465   57.11974  1.33360746  0.5892699921
Haribo Happy Cola                  0.465   34.15896  1.11167365  0.6257697808
Haribo Sour Bears                  0.465   51.41243  1.46152952  0.5073691482
Haribo Twin Snakes                 0.465   42.17877  1.66849016  0.3748646265
Hershey's Kisses                   0.093   55.37545  0.37722675  1.5654519145
Hershey's Krackel                  0.918   62.28448 -3.04788356  0.6850792787
Hershey's Milk Chocolate           0.918   56.49050 -2.11696417  0.2504568891
Hershey's Special Dark             0.918   59.23612 -2.17850376  0.2898570052
Jawbusters                         0.511   28.12744  2.62491587 -0.6343671618
Junior Mints                       0.511   57.21925 -0.16010610  1.6194428347
Kit Kat                            0.511   76.76860 -2.87086546  0.9069655335
Laffy Taffy                        0.116   41.38956  1.65450042 -0.2379605144
Lemonhead                          0.104   39.14106  2.33564695 -1.2553404646
Lifesavers big ring gummies        0.279   52.91139  1.19528766 -0.0783610246
Peanut butter M&amp;M's                0.651   71.46505 -1.52223814  1.9291395890
M&amp;M's                              0.651   66.57458 -0.76747561  1.2573539136
Mike &amp; Ike                         0.325   46.41172  1.57487290  0.0664259746
Milk Duds                          0.511   55.06407 -0.76836937  0.4192793946
Milky Way                          0.651   73.09956 -3.69272218 -2.4933313173
Milky Way Midnight                 0.441   60.80070 -3.23036513 -2.8201031327
Milky Way Simply Caramel           0.860   64.35334 -3.04936226 -1.1774777304
Mounds                             0.860   47.82975 -1.81292795  0.2120726312
Mr Good Bar                        0.918   54.52645 -2.67327849  0.9217207344
Nerds                              0.325   55.35405  1.93426895 -0.9133307225
Nestle Butterfinger                0.767   70.73564 -2.97855081  0.8798835368
Nestle Crunch                      0.767   66.47068 -2.92740488  0.8119013154
Nik L Nip                          0.976   22.44534  1.63985272  0.4210217322
Now &amp; Later                        0.325   39.44680  1.98070982  0.5117150919
Payday                             0.767   46.29660 -2.39180556 -1.4839637512
Peanut M&amp;Ms                        0.651   69.48379 -1.38897069  2.0947188031
Pixie Sticks                       0.023   37.72234  1.67042227  0.8969792365
Pop Rocks                          0.837   41.26551  1.76879348 -0.8060325640
Red vines                          0.116   37.34852  2.12406849  0.1366822960
Reese's Miniatures                 0.279   81.86626 -1.55210251  1.9287569793
Reese's Peanut Butter cup          0.651   84.18029 -2.28427985  1.4648923293
Reese's pieces                     0.651   73.43499 -1.40590761  2.3077984818
Reese's stuffed with pieces        0.651   72.88790 -2.13382398  1.0787289654
Ring pop                           0.965   35.29076  1.19274412 -1.7069749284
Rolo                               0.860   65.71629 -1.61259322  0.1773734932
Root Beer Barrels                  0.069   29.70369  2.10440254 -0.8711340556
Runts                              0.279   42.84914  2.25699185 -1.1223199934
Sixlets                            0.081   34.72200  0.81799664  1.1888290122
Skittles original                  0.220   63.08514  1.29259129  0.2263705137
Skittles wildberry                 0.220   55.10370  1.47148517  0.1118354559
Nestle Smarties                    0.976   37.88719 -0.27556563  1.3792344137
Smarties candy                     0.116   45.99583  2.60115214 -0.6047947520
Snickers                           0.651   76.67378 -4.39576792 -1.7919312516
Snickers Crisper                   0.651   59.52925 -4.01457335 -0.0347673522
Sour Patch Kids                    0.116   59.86400  1.81551769  0.8879445215
Sour Patch Tricksters              0.116   52.82595  1.97326660  0.7869473239
Starburst                          0.220   67.03763  1.50658493  0.9437290830
Strawberry bon bons                0.058   34.57899  2.80647837 -1.0331193111
Sugar Babies                       0.767   33.43755 -0.01900559 -0.8219542293
Sugar Daddy                        0.325   32.23100  0.19642038 -1.2073694698
Super Bubble                       0.116   27.30386  1.99242820 -0.3915898648
Swedish Fish                       0.755   54.86111  1.00547407  0.5003327040
Tootsie Pop                        0.325   48.98265  0.84734171 -1.1060686710
Tootsie Roll Juniors               0.511   43.06890 -0.40463667  0.5848580362
Tootsie Roll Midgies               0.011   45.73675  0.66730732  1.3709464980
Tootsie Roll Snack Bars            0.325   49.65350 -1.31149842  0.0009721286
Trolli Sour Bites                  0.255   47.17323  1.85048456  0.5304055168
Twix                               0.906   81.64291 -4.12909044 -0.2180299573
Twizzlers                          0.116   45.46628  1.56312584 -0.1794588354
Warheads                           0.116   39.01190  2.30707033 -1.2940268825
Welch's Fruit Snacks               0.313   44.37552  1.84808801  0.5022006184
Werther's Original Caramel         0.267   41.90431  0.68420363 -2.0146385440
Whoppers                           0.848   49.52411 -1.42549552  1.3654147702
                                     PC3
100 Grand                   -2.186308676
3 Musketeers                 1.412198551
One dime                     2.060771178
One quarter                  1.476492844
Air Heads                   -0.929389343
Almond Joy                   0.858108916
Baby Ruth                    1.347834706
Boston Baked Beans           0.941899950
Candy Corn                  -0.840681586
Caramel Apple Pops          -0.207020586
Charleston Chew              1.675469334
Chewey Lemonhead Fruit Mix  -0.909617411
Chiclets                     1.000422079
Dots                        -0.967135199
Dum Dums                    -0.385372660
Fruit Chews                  0.978626618
Fun Dip                     -0.719415821
Gobstopper                  -1.873874385
Haribo Gold Bears           -0.431929774
Haribo Happy Cola            0.054459647
Haribo Sour Bears           -0.379443632
Haribo Twin Snakes          -0.294528131
Hershey's Kisses             1.104739528
Hershey's Krackel           -1.154357778
Hershey's Milk Chocolate     0.218316614
Hershey's Special Dark       0.193067056
Jawbusters                   0.114043053
Junior Mints                 0.442156347
Kit Kat                     -0.545771148
Laffy Taffy                  1.217408326
Lemonhead                    1.125823900
Lifesavers big ring gummies  0.814040659
Peanut butter M&amp;M's         -0.815897653
M&amp;M's                       -1.260658369
Mike &amp; Ike                  -1.114406454
Milk Duds                   -0.137573021
Milky Way                    0.843423990
Milky Way Midnight           0.902884388
Milky Way Simply Caramel    -1.382617058
Mounds                       0.636094539
Mr Good Bar                  0.997161433
Nerds                       -1.670281710
Nestle Butterfinger          0.348599786
Nestle Crunch               -0.747159803
Nik L Nip                   -0.083217936
Now &amp; Later                  0.460099768
Payday                       2.091687409
Peanut M&amp;Ms                 -0.260214925
Pixie Sticks                 1.394703254
Pop Rocks                   -1.567639814
Red vines                   -0.115183020
Reese's Miniatures           1.884620322
Reese's Peanut Butter cup   -0.156138940
Reese's pieces               0.136661895
Reese's stuffed with pieces -0.673152403
Ring pop                    -1.423826969
Rolo                        -1.931879747
Root Beer Barrels           -0.594335570
Runts                       -1.557678507
Sixlets                      1.093105891
Skittles original           -1.306145308
Skittles wildberry          -1.232745536
Nestle Smarties             -0.080047831
Smarties candy               0.003482896
Snickers                     1.434654778
Snickers Crisper            -1.089868643
Sour Patch Kids              0.863881832
Sour Patch Tricksters        0.928605869
Starburst                    0.487658690
Strawberry bon bons         -0.524069119
Sugar Babies                -1.802826526
Sugar Daddy                  0.520140143
Super Bubble                 1.481310204
Swedish Fish                -1.068588828
Tootsie Pop                 -0.480874078
Tootsie Roll Juniors         0.836999949
Tootsie Roll Midgies         1.179339290
Tootsie Roll Snack Bars      0.885976952
Trolli Sour Bites            0.254559391
Twix                        -1.943536689
Twizzlers                    1.179917535
Warheads                     1.004249910
Welch's Fruit Snacks         0.213204782
Werther's Original Caramel   0.506488679
Whoppers                    -2.759982292</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_data)<span class="sc">+</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(PC1, PC2, <span class="at">label=</span><span class="fu">rownames</span>(my_data))<span class="sc">+</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col=</span>my_cols)<span class="sc">+</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">col=</span>my_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: ggrepel: 21 unlabeled data points (too many overlaps). Consider
increasing max.overlaps</code></pre>
</div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Make this a bit nicer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(my_data) <span class="sc">+</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">x=</span>PC1, <span class="at">y=</span>PC2, </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">size=</span>winpercent<span class="sc">/</span><span class="dv">100</span>,  </span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">text=</span><span class="fu">rownames</span>(my_data),</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">label=</span><span class="fu">rownames</span>(my_data)) <span class="sc">+</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_point</span>(<span class="at">col=</span>my_cols)</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_text_repel</span>(<span class="at">size=</span><span class="fl">3.3</span>, <span class="at">col=</span>my_cols, <span class="at">max.overlaps =</span> <span class="dv">7</span>)  <span class="sc">+</span> </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Halloween Candy PCA Space"</span>,</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span><span class="st">"Colored by type: chocolate bar (orange), chocolate other (lightblue), fruity (pink), other (black)"</span>,</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption=</span><span class="st">"Data from 538"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: ggrepel: 39 unlabeled data points (too many overlaps). Consider
increasing max.overlaps</code></pre>
</div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(plotly)</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="co">#ggplotly(p)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>How do the original variable s contribute to our PCs? For this we look at the loadings component of our results object. i.e.&nbsp;“the <code>pca$rotation</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>pca<span class="sc">$</span>rotation[,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       chocolate           fruity          caramel   peanutyalmondy 
      -0.4019466        0.3683883       -0.2299709       -0.2407155 
          nougat crispedricewafer             hard              bar 
      -0.2268102       -0.2215182        0.2111587       -0.3947433 
        pluribus     sugarpercent     pricepercent       winpercent 
       0.2600041       -0.1083088       -0.3207361       -0.3298035 </code></pre>
</div>
</div>
<p>Make a barplot with ggplot and order the bars by their value. Recall that you need a data.frame as input for ggplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pca<span class="sc">$</span>rotation)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "chocolate"        "fruity"           "caramel"          "peanutyalmondy"  
 [5] "nougat"           "crispedricewafer" "hard"             "bar"             
 [9] "pluribus"         "sugarpercent"     "pricepercent"     "winpercent"      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(res)<span class="sc">+</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(PC1,<span class="fu">reorder</span>(<span class="fu">row.names</span>(res),PC1))<span class="sc">+</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q24. What original variables are picked up strongly by PC1 in the positive direction? Do these make sense to you?</p>
</blockquote>
<p>Fruit, Pluribus and Hard are all picked up in the + direction and these do make sense based on the correlation structure in the dataset. If you are a fruity candy you will tend to be hard and come in a packet with multiple candies in it(pluribus).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>